<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Errors;


class Details
{
    /**
     *
     * @var string $field
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('field')]
    public string $field;

    /**
     *
     * @var string $issue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issue')]
    public string $issue;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     * @param  string  $field
     * @param  string  $issue
     * @param  string  $message
     * @phpstan-pure
     */
    public function __construct(string $field, string $issue, string $message)
    {
        $this->field = $field;
        $this->issue = $issue;
        $this->message = $message;
    }
}