<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 68b65cc72dbd
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Errors;

class ErrorResponseThrowable extends \RuntimeException
{
    public ErrorResponse $container;

    public function __construct(string $message, int $statusCode, ErrorResponse $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}