<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Errors;

use Luqra\Now\Utils;
class ErrorResponse
{
    /**
     *
     * @var Error $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Errors\Error')]
    public Error $error;

    /**
     * @param  Error  $error
     * @phpstan-pure
     */
    public function __construct(Error $error)
    {
        $this->error = $error;
    }

    public function toException(): ErrorResponseThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ErrorResponseThrowable($message, (int) $code, $this);
    }
}