<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6f229875029
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

use Psr\Http\Message\ResponseInterface;

interface AfterErrorHook
{
    public function afterError(AfterErrorContext $context, ?ResponseInterface $response, \Throwable $exception): ErrorResponseContext;
}
