<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3f9dd7b31c3a
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

use Psr\Http\Message\ResponseInterface;

interface AfterSuccessHook
{
    public function afterSuccess(AfterSuccessContext $context, ResponseInterface $response): ResponseInterface;
}
