<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 62d4f2980d2d
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

class BeforeRequestContext extends HookContext
{
    public function __construct(HookContext $hookCtx)
    {
        parent::__construct($hookCtx->config, $hookCtx->baseURL, $hookCtx->operationID, $hookCtx->oauth2Scopes, $hookCtx->securitySource);
    }

    /**
     * @param  string  $name
     * @param  array<mixed>  $args
     * @return mixed
     */
    public function __call($name, $args): mixed
    {
        if ($name === 'securitySource') {
            return call_user_func_array($this->securitySource, $args);
        }

        return null;
    }
}
