<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2ba4c41dd54c
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;
use Psr\Http\Message\ResponseInterface;

class ErrorResponseContext
{
    public ?ResponseInterface $response;
    public ?\Throwable $e;

    public function __construct(?ResponseInterface $response, ?\Throwable $e)
    {
        $this->response = $response;
        $this->e = $e;
    }
}
