<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0ae1bdaec63f
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

class FailEarlyException extends \Exception
{
}
