<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16729a806274
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

use Luqra\LuqraNowPhp\SDKConfiguration;

interface SDKInitHook
{
    public function sdkInit(SDKConfiguration $config): SDKConfiguration;
}
