<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aad5e2b1d06f
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Hooks;

class TokenResponse
{
    public ?string $accessToken;
    public ?string $tokenType;
    public ?int $expiresIn;
}
