<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum AmountInputMode: string
{
    case Gross = 'GROSS';
    case Net = 'NET';
}
