<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0277d60b860e
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ContactSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
