<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class Contact
{
    /**
     *
     * @var GetV0PaymentsEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV0PaymentsEntityType')]
    public GetV0PaymentsEntityType $entityType;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName;

    /**
     * @param  GetV0PaymentsEntityType  $entityType
     * @param  string  $firstName
     * @param  string  $id
     * @param  string  $lastName
     * @param  ?string  $companyName
     * @phpstan-pure
     */
    public function __construct(GetV0PaymentsEntityType $entityType, string $firstName, string $id, string $lastName, ?string $companyName = null)
    {
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->id = $id;
        $this->lastName = $lastName;
        $this->companyName = $companyName;
    }
}