<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ContactBankAccount
{
    /**
     *
     * @var string $achAccountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achAccountNumber')]
    public string $achAccountNumber;

    /**
     *
     * @var string $achRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achRoutingNumber')]
    public string $achRoutingNumber;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ContactSubType $subType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ContactSubType')]
    public ContactSubType $subType;

    /**
     *
     * @var ?string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankName')]
    public ?string $bankName = null;

    /**
     *
     * @var ?string $swiftCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('swiftCode')]
    public ?string $swiftCode = null;

    /**
     * @param  string  $achAccountNumber
     * @param  string  $achRoutingNumber
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ContactSubType  $subType
     * @param  ?string  $bankName
     * @param  ?string  $swiftCode
     * @phpstan-pure
     */
    public function __construct(string $achAccountNumber, string $achRoutingNumber, ContactSubType $subType, ?string $bankName = null, ?string $swiftCode = null)
    {
        $this->achAccountNumber = $achAccountNumber;
        $this->achRoutingNumber = $achRoutingNumber;
        $this->subType = $subType;
        $this->bankName = $bankName;
        $this->swiftCode = $swiftCode;
    }
}