<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateWebhookRequest
{
    /**
     * $subscribedEvents
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequest> $subscribedEvents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscribedEvents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequest>')]
    public array $subscribedEvents;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequest>  $subscribedEvents
     * @param  string  $url
     * @phpstan-pure
     */
    public function __construct(array $subscribedEvents, string $url)
    {
        $this->subscribedEvents = $subscribedEvents;
        $this->url = $url;
    }
}