<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 81f42f54697c
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum CreateContactEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
