<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class CreatePaymentRequest
{
    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public string $idempotencyKey;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public CreatePaymentRequestBody $body;

    /**
     * @param  string  $idempotencyKey
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $idempotencyKey, CreatePaymentRequestBody $body)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->body = $body;
    }
}