<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum CreateWebhookSubscribedEventPaymentWildcardResponse: string
{
    case PaymentWildcard = 'payment.*';
}
