<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateContactData
{
    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     * @param  string  $contactId
     * @param  \DateTime  $createdAt
     * @phpstan-pure
     */
    public function __construct(string $contactId, \DateTime $createdAt)
    {
        $this->contactId = $contactId;
        $this->createdAt = $createdAt;
    }
}