<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 13c96ef07634
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum CreateContactSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
