<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateWebhookRequest
{
    /**
     * $subscribedEvents
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequestEnum> $subscribedEvents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscribedEvents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequestEnum>')]
    public array $subscribedEvents;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventRequestEnum>  $subscribedEvents
     * @param  string  $url
     * @param  ?string  $label
     * @phpstan-pure
     */
    public function __construct(array $subscribedEvents, string $url, ?string $label = null)
    {
        $this->subscribedEvents = $subscribedEvents;
        $this->url = $url;
        $this->label = $label;
    }
}