<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateContactRequest
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateContactBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateContactBankAccount')]
    public CreateContactBankAccount $bankAccount;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateContactEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateContactEntityType')]
    public CreateContactEntityType $entityType;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateContactLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateContactLegalAddress')]
    public CreateContactLegalAddress $legalAddress;

    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateContactBankAccount  $bankAccount
     * @param  string  $email
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateContactEntityType  $entityType
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateContactLegalAddress  $legalAddress
     * @param  string  $originatorId
     * @param  ?string  $companyName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(CreateContactBankAccount $bankAccount, string $email, CreateContactEntityType $entityType, string $firstName, string $lastName, CreateContactLegalAddress $legalAddress, string $originatorId, ?string $companyName = null, ?string $phoneNumber = null)
    {
        $this->bankAccount = $bankAccount;
        $this->email = $email;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->originatorId = $originatorId;
        $this->companyName = $companyName;
        $this->phoneNumber = $phoneNumber;
    }
}