<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 47f4335cff47
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum CreateWebhookSubscribedEventResponse: string
{
    case StatementGenerated = 'STATEMENT_GENERATED';
}
