<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** CreatePaymentResponseBody - Default Response */
class CreatePaymentResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreatePaymentData')]
    public CreatePaymentData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreatePaymentMeta')]
    public CreatePaymentMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreatePaymentMeta  $meta
     * @phpstan-pure
     */
    public function __construct(CreatePaymentData $data, CreatePaymentMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}