<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c8c9b2b4a5f7
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateContactBankAccount
{
    /**
     *
     * @var string $achAccountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achAccountNumber')]
    public string $achAccountNumber;

    /**
     *
     * @var string $achRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achRoutingNumber')]
    public string $achRoutingNumber;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateContactSubType $subType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateContactSubType')]
    public CreateContactSubType $subType;

    /**
     *
     * @var ?string $swiftCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('swiftCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $swiftCode = null;

    /**
     * @param  string  $achAccountNumber
     * @param  string  $achRoutingNumber
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateContactSubType  $subType
     * @param  ?string  $swiftCode
     * @phpstan-pure
     */
    public function __construct(string $achAccountNumber, string $achRoutingNumber, CreateContactSubType $subType, ?string $swiftCode = null)
    {
        $this->achAccountNumber = $achAccountNumber;
        $this->achRoutingNumber = $achRoutingNumber;
        $this->subType = $subType;
        $this->swiftCode = $swiftCode;
    }
}