<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** CreatePaymentResponseBody - Default Response */
class CreatePaymentResponseBody
{
    /**
     *
     * @var CreatePaymentData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\CreatePaymentData')]
    public CreatePaymentData $data;

    /**
     *
     * @var CreatePaymentMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\CreatePaymentMeta')]
    public CreatePaymentMeta $meta;

    /**
     * @param  CreatePaymentData  $data
     * @param  CreatePaymentMeta  $meta
     * @phpstan-pure
     */
    public function __construct(CreatePaymentData $data, CreatePaymentMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}