<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93ef6e7bbe8d
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** CreateWebhookResponseBody - Default Response */
class CreateWebhookResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateWebhookData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookData')]
    public CreateWebhookData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\CreateWebhookMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookMeta')]
    public CreateWebhookMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateWebhookData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\CreateWebhookMeta  $meta
     * @phpstan-pure
     */
    public function __construct(CreateWebhookData $data, CreateWebhookMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}