<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad765a29d50a
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum CreatePaymentDirection: string
{
    case Inbound = 'INBOUND';
    case Outbound = 'OUTBOUND';
}
