<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** CreateContactResponseBody - Default Response */
class CreateContactResponseBody
{
    /**
     *
     * @var CreateContactData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\CreateContactData')]
    public CreateContactData $data;

    /**
     *
     * @var CreateContactMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\CreateContactMeta')]
    public CreateContactMeta $meta;

    /**
     * @param  CreateContactData  $data
     * @param  CreateContactMeta  $meta
     * @phpstan-pure
     */
    public function __construct(CreateContactData $data, CreateContactMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}