<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class CreateWebhookData
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    public bool $enabled;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    public string $secret;

    /**
     * $subscribedEvents
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardResponse|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventResponseEnum> $subscribedEvents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscribedEvents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardResponse|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventResponseEnum>')]
    public array $subscribedEvents;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public ?string $label;

    /**
     * @param  \DateTime  $createdAt
     * @param  bool  $enabled
     * @param  string  $id
     * @param  string  $secret
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventPaymentWildcardResponse|\Luqra\LuqraNowPhp\Models\Operations\CreateWebhookSubscribedEventResponseEnum>  $subscribedEvents
     * @param  string  $url
     * @param  ?string  $label
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, bool $enabled, string $id, string $secret, array $subscribedEvents, string $url, ?string $label = null)
    {
        $this->createdAt = $createdAt;
        $this->enabled = $enabled;
        $this->id = $id;
        $this->secret = $secret;
        $this->subscribedEvents = $subscribedEvents;
        $this->url = $url;
        $this->label = $label;
    }
}