<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c34f038ecdfb
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetPaymentFailureCode: string
{
    case InternalError = 'INTERNAL_ERROR';
    case InvalidContactData = 'INVALID_CONTACT_DATA';
    case InvalidOriginatorData = 'INVALID_ORIGINATOR_DATA';
}
