<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 91040ca6b9ef
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetPaymentDirection: string
{
    case Inbound = 'INBOUND';
    case Outbound = 'OUTBOUND';
}
