<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class GetPaymentData
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentContact $contact
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contact')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentContact')]
    public GetPaymentContact $contact;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentDirection $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentDirection')]
    public GetPaymentDirection $direction;

    /**
     * In minor units (cents)
     *
     * @var int $feeAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeAmount')]
    public int $feeAmount;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginator $originator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginator')]
    public GetPaymentOriginator $originator;

    /**
     * In minor units (cents)
     *
     * @var int $paymentAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentAmount')]
    public int $paymentAmount;

    /**
     *
     * @var string $paymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentId')]
    public string $paymentId;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentPaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentRail')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentPaymentRail')]
    public GetPaymentPaymentRail $paymentRail;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentStatus')]
    public GetPaymentStatus $status;

    /**
     *
     * @var ?\DateTime $completedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedAt')]
    public ?\DateTime $completedAt;

    /**
     *
     * @var ?string $externalPaymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalPaymentId')]
    public ?string $externalPaymentId;

    /**
     *
     * @var ?\DateTime $failedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failedAt')]
    public ?\DateTime $failedAt;

    /**
     *
     * @var ?string $failureReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureReason')]
    public ?string $failureReason;

    /**
     *
     * @var ?string $paymentNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentNote')]
    public ?string $paymentNote;

    /**
     *
     * @var ?string $returnReasonCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('returnReasonCode')]
    public ?string $returnReasonCode;

    /**
     *
     * @var ?\DateTime $returnedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('returnedAt')]
    public ?\DateTime $returnedAt;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentContact  $contact
     * @param  \DateTime  $createdAt
     * @param  string  $currencyCode
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentDirection  $direction
     * @param  int  $feeAmount
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginator  $originator
     * @param  int  $paymentAmount
     * @param  string  $paymentId
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentPaymentRail  $paymentRail
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentStatus  $status
     * @param  ?\DateTime  $completedAt
     * @param  ?string  $externalPaymentId
     * @param  ?\DateTime  $failedAt
     * @param  ?string  $failureReason
     * @param  ?string  $paymentNote
     * @param  ?string  $returnReasonCode
     * @param  ?\DateTime  $returnedAt
     * @phpstan-pure
     */
    public function __construct(GetPaymentContact $contact, \DateTime $createdAt, string $currencyCode, GetPaymentDirection $direction, int $feeAmount, GetPaymentOriginator $originator, int $paymentAmount, string $paymentId, GetPaymentPaymentRail $paymentRail, GetPaymentStatus $status, ?\DateTime $completedAt = null, ?string $externalPaymentId = null, ?\DateTime $failedAt = null, ?string $failureReason = null, ?string $paymentNote = null, ?string $returnReasonCode = null, ?\DateTime $returnedAt = null)
    {
        $this->contact = $contact;
        $this->createdAt = $createdAt;
        $this->currencyCode = $currencyCode;
        $this->direction = $direction;
        $this->feeAmount = $feeAmount;
        $this->originator = $originator;
        $this->paymentAmount = $paymentAmount;
        $this->paymentId = $paymentId;
        $this->paymentRail = $paymentRail;
        $this->status = $status;
        $this->completedAt = $completedAt;
        $this->externalPaymentId = $externalPaymentId;
        $this->failedAt = $failedAt;
        $this->failureReason = $failureReason;
        $this->paymentNote = $paymentNote;
        $this->returnReasonCode = $returnReasonCode;
        $this->returnedAt = $returnedAt;
    }
}