<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetPaymentResponseBody - Default Response */
class GetPaymentResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentData')]
    public GetPaymentData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentMeta')]
    public GetPaymentMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentMeta  $meta
     * @phpstan-pure
     */
    public function __construct(GetPaymentData $data, GetPaymentMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}