<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class GetPaymentOriginator
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\OriginatorBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\OriginatorBankAccount')]
    public OriginatorBankAccount $bankAccount;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginatorEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginatorEntityType')]
    public GetPaymentOriginatorEntityType $entityType;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public ?string $lastName = null;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\OriginatorBankAccount  $bankAccount
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetPaymentOriginatorEntityType  $entityType
     * @param  string  $id
     * @param  ?string  $companyName
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @phpstan-pure
     */
    public function __construct(OriginatorBankAccount $bankAccount, GetPaymentOriginatorEntityType $entityType, string $id, ?string $companyName = null, ?string $firstName = null, ?string $lastName = null)
    {
        $this->bankAccount = $bankAccount;
        $this->entityType = $entityType;
        $this->id = $id;
        $this->companyName = $companyName;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
    }
}