<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c862a54d621e
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetPaymentContactEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
