<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetPaymentFailureCode: string
{
    case InternalError = 'INTERNAL_ERROR';
    case InvalidPartyData = 'INVALID_PARTY_DATA';
}
