<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 333890f48a62
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetPaymentOriginatorEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
