<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5db6b2dafc9e
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class GetStatementDownloadUrlData
{
    /**
     *
     * @var \DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresAt')]
    public \DateTime $expiresAt;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * @param  \DateTime  $expiresAt
     * @param  string  $url
     * @phpstan-pure
     */
    public function __construct(\DateTime $expiresAt, string $url)
    {
        $this->expiresAt = $expiresAt;
        $this->url = $url;
    }
}