<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c91706e92933
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetStatementDownloadUrlResponseBody - Default Response */
class GetStatementDownloadUrlResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlData')]
    public GetStatementDownloadUrlData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlMeta')]
    public GetStatementDownloadUrlMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetStatementDownloadUrlMeta  $meta
     * @phpstan-pure
     */
    public function __construct(GetStatementDownloadUrlData $data, GetStatementDownloadUrlMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}