<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class GetV1ContactsData
{
    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     * @param  string  $contactId
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  ?string  $email
     * @phpstan-pure
     */
    public function __construct(string $contactId, string $firstName, string $lastName, ?string $email = null)
    {
        $this->contactId = $contactId;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
    }
}