<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class GetV0PaymentsData
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     *
     * @var GetV0PaymentsDirection $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV0PaymentsDirection')]
    public GetV0PaymentsDirection $direction;

    /**
     * In minor units (cents)
     *
     * @var int $feeAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeAmount')]
    public int $feeAmount;

    /**
     *
     * @var Originator $originator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Originator')]
    public Originator $originator;

    /**
     * In minor units (cents)
     *
     * @var int $paymentAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentAmount')]
    public int $paymentAmount;

    /**
     *
     * @var string $paymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentId')]
    public string $paymentId;

    /**
     *
     * @var PaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentRail')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PaymentRail')]
    public PaymentRail $paymentRail;

    /**
     *
     * @var GetV0PaymentsStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV0PaymentsStatus')]
    public GetV0PaymentsStatus $status;

    /**
     *
     * @var ?Contact $contact
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contact')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Contact|null')]
    public ?Contact $contact;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $currencyCode
     * @param  GetV0PaymentsDirection  $direction
     * @param  int  $feeAmount
     * @param  Originator  $originator
     * @param  int  $paymentAmount
     * @param  string  $paymentId
     * @param  PaymentRail  $paymentRail
     * @param  GetV0PaymentsStatus  $status
     * @param  ?Contact  $contact
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $currencyCode, GetV0PaymentsDirection $direction, int $feeAmount, Originator $originator, int $paymentAmount, string $paymentId, PaymentRail $paymentRail, GetV0PaymentsStatus $status, ?Contact $contact = null)
    {
        $this->createdAt = $createdAt;
        $this->currencyCode = $currencyCode;
        $this->direction = $direction;
        $this->feeAmount = $feeAmount;
        $this->originator = $originator;
        $this->paymentAmount = $paymentAmount;
        $this->paymentId = $paymentId;
        $this->paymentRail = $paymentRail;
        $this->status = $status;
        $this->contact = $contact;
    }
}