<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\NowPhp\Models\Operations;

use Luqra\NowPhp\Utils\SpeakeasyMetadata;
class GetV1ContactsRequest
{
    /**
     *
     * @var string $originatorId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * @param  string  $originatorId
     * @param  ?string  $search
     * @phpstan-pure
     */
    public function __construct(string $originatorId, ?string $search = null)
    {
        $this->originatorId = $originatorId;
        $this->search = $search;
    }
}