<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetV0OriginatorsResponseBody - Default Response */
class GetV0OriginatorsResponseBody
{
    /**
     * $data
     *
     * @var array<GetV0OriginatorsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\GetV0OriginatorsData>')]
    public array $data;

    /**
     *
     * @var GetV0OriginatorsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV0OriginatorsMeta')]
    public GetV0OriginatorsMeta $meta;

    /**
     * @param  array<GetV0OriginatorsData>  $data
     * @param  GetV0OriginatorsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, GetV0OriginatorsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}