<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** GetV1ContactsResponseBody - Default Response */
class GetV1ContactsResponseBody
{
    /**
     * $data
     *
     * @var array<GetV1ContactsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\Now\Models\Operations\GetV1ContactsData>')]
    public array $data;

    /**
     *
     * @var GetV1ContactsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1ContactsMeta')]
    public GetV1ContactsMeta $meta;

    /**
     * @param  array<GetV1ContactsData>  $data
     * @param  GetV1ContactsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, GetV1ContactsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}