<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


enum GetV0PaymentsDirection: string
{
    case Inbound = 'INBOUND';
    case Outbound = 'OUTBOUND';
}
