<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetV0PaymentsResponseBody - Default Response */
class GetV0PaymentsResponseBody
{
    /**
     * $data
     *
     * @var array<GetV0PaymentsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\GetV0PaymentsData>')]
    public array $data;

    /**
     *
     * @var GetV0PaymentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV0PaymentsMeta')]
    public GetV0PaymentsMeta $meta;

    /**
     * @param  array<GetV0PaymentsData>  $data
     * @param  GetV0PaymentsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, GetV0PaymentsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}