<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** GetV1PaymentsItemIdResponseBody - Default Response */
class GetV1PaymentsItemIdResponseBody
{
    /**
     *
     * @var GetV1PaymentsItemIdData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdData')]
    public GetV1PaymentsItemIdData $data;

    /**
     *
     * @var GetV1PaymentsItemIdMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdMeta')]
    public GetV1PaymentsItemIdMeta $meta;

    /**
     * @param  GetV1PaymentsItemIdData  $data
     * @param  GetV1PaymentsItemIdMeta  $meta
     * @phpstan-pure
     */
    public function __construct(GetV1PaymentsItemIdData $data, GetV1PaymentsItemIdMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}