<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class GetV1PaymentsItemIdData
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var GetV1PaymentsItemIdStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdStatus')]
    public GetV1PaymentsItemIdStatus $status;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $netAmountMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('netAmountMinorUnits')]
    public string $netAmountMinorUnits;

    /**
     *
     * @var string $feeMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeMinorUnits')]
    public string $feeMinorUnits;

    /**
     *
     * @var string $reserveMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reserveMinorUnits')]
    public string $reserveMinorUnits;

    /**
     *
     * @var string $inputAmountMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('inputAmountMinorUnits')]
    public string $inputAmountMinorUnits;

    /**
     *
     * @var GetV1PaymentsItemIdAmountInputMode $amountInputMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amountInputMode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdAmountInputMode')]
    public GetV1PaymentsItemIdAmountInputMode $amountInputMode;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     *
     * @var GetV1PaymentsItemIdPaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentRail')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdPaymentRail')]
    public GetV1PaymentsItemIdPaymentRail $paymentRail;

    /**
     *
     * @var GetV1PaymentsItemIdDirection $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV1PaymentsItemIdDirection')]
    public GetV1PaymentsItemIdDirection $direction;

    /**
     *
     * @var string $sourceAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceAccountId')]
    public string $sourceAccountId;

    /**
     *
     * @var string $destinationAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationAccountId')]
    public string $destinationAccountId;

    /**
     *
     * @var string $originatorPartyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorPartyId')]
    public string $originatorPartyId;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     *
     * @var ?string $externalPaymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalPaymentId')]
    public ?string $externalPaymentId;

    /**
     * @param  string  $id
     * @param  GetV1PaymentsItemIdStatus  $status
     * @param  \DateTime  $createdAt
     * @param  string  $netAmountMinorUnits
     * @param  string  $feeMinorUnits
     * @param  string  $reserveMinorUnits
     * @param  string  $inputAmountMinorUnits
     * @param  GetV1PaymentsItemIdAmountInputMode  $amountInputMode
     * @param  string  $currencyCode
     * @param  GetV1PaymentsItemIdPaymentRail  $paymentRail
     * @param  GetV1PaymentsItemIdDirection  $direction
     * @param  string  $sourceAccountId
     * @param  string  $destinationAccountId
     * @param  string  $originatorPartyId
     * @param  ?string  $description
     * @param  ?string  $externalPaymentId
     * @phpstan-pure
     */
    public function __construct(string $id, GetV1PaymentsItemIdStatus $status, \DateTime $createdAt, string $netAmountMinorUnits, string $feeMinorUnits, string $reserveMinorUnits, string $inputAmountMinorUnits, GetV1PaymentsItemIdAmountInputMode $amountInputMode, string $currencyCode, GetV1PaymentsItemIdPaymentRail $paymentRail, GetV1PaymentsItemIdDirection $direction, string $sourceAccountId, string $destinationAccountId, string $originatorPartyId, ?string $description = null, ?string $externalPaymentId = null)
    {
        $this->id = $id;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->netAmountMinorUnits = $netAmountMinorUnits;
        $this->feeMinorUnits = $feeMinorUnits;
        $this->reserveMinorUnits = $reserveMinorUnits;
        $this->inputAmountMinorUnits = $inputAmountMinorUnits;
        $this->amountInputMode = $amountInputMode;
        $this->currencyCode = $currencyCode;
        $this->paymentRail = $paymentRail;
        $this->direction = $direction;
        $this->sourceAccountId = $sourceAccountId;
        $this->destinationAccountId = $destinationAccountId;
        $this->originatorPartyId = $originatorPartyId;
        $this->description = $description;
        $this->externalPaymentId = $externalPaymentId;
    }
}