<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class GetV0OriginatorsData
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var GetV0OriginatorsEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV0OriginatorsEntityType')]
    public GetV0OriginatorsEntityType $entityType;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var GetV0OriginatorsLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV0OriginatorsLegalAddress')]
    public GetV0OriginatorsLegalAddress $legalAddress;

    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?GetV0OriginatorsBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV0OriginatorsBankAccount|null')]
    public ?GetV0OriginatorsBankAccount $bankAccount = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public ?string $phoneNumber = null;

    /**
     * @param  \DateTime  $createdAt
     * @param  GetV0OriginatorsEntityType  $entityType
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  GetV0OriginatorsLegalAddress  $legalAddress
     * @param  string  $originatorId
     * @param  ?GetV0OriginatorsBankAccount  $bankAccount
     * @param  ?string  $companyName
     * @param  ?string  $email
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, GetV0OriginatorsEntityType $entityType, string $firstName, string $lastName, GetV0OriginatorsLegalAddress $legalAddress, string $originatorId, ?GetV0OriginatorsBankAccount $bankAccount = null, ?string $companyName = null, ?string $email = null, ?string $phoneNumber = null)
    {
        $this->createdAt = $createdAt;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->originatorId = $originatorId;
        $this->bankAccount = $bankAccount;
        $this->companyName = $companyName;
        $this->email = $email;
        $this->phoneNumber = $phoneNumber;
    }
}