<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetV1PaymentsResponseBody - Default Response */
class GetV1PaymentsResponseBody
{
    /**
     * $data
     *
     * @var array<GetV1PaymentsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\GetV1PaymentsData>')]
    public array $data;

    /**
     *
     * @var GetV1PaymentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetV1PaymentsMeta')]
    public GetV1PaymentsMeta $meta;

    /**
     * @param  array<GetV1PaymentsData>  $data
     * @param  GetV1PaymentsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, GetV1PaymentsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}