<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetV1PaymentsStatus: string
{
    case AwaitingConfirmation = 'AWAITING_CONFIRMATION';
    case Scheduled = 'SCHEDULED';
    case Processing = 'PROCESSING';
    case Completed = 'COMPLETED';
    case Failed = 'FAILED';
    case Canceled = 'CANCELED';
    case Returned = 'RETURNED';
}
