<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\NowPhp\Models\Operations;

use Luqra\NowPhp\Utils\SpeakeasyMetadata;
class GetV1PaymentsRequest
{
    /**
     *
     * @var ?Status $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?Status $status = null;

    /**
     *
     * @var ?string $partyId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=partyId')]
    public ?string $partyId = null;

    /**
     *
     * @var ?QueryParamDirection $direction
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=direction')]
    public ?QueryParamDirection $direction = null;

    /**
     *
     * @var ?\DateTime $createdFrom
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=createdFrom,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdFrom = null;

    /**
     *
     * @var ?\DateTime $createdTo
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=createdTo,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdTo = null;

    /**
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?int  $page
     * @param  ?int  $limit
     * @param  ?Status  $status
     * @param  ?string  $partyId
     * @param  ?QueryParamDirection  $direction
     * @param  ?\DateTime  $createdFrom
     * @param  ?\DateTime  $createdTo
     * @phpstan-pure
     */
    public function __construct(?Status $status = null, ?string $partyId = null, ?QueryParamDirection $direction = null, ?\DateTime $createdFrom = null, ?\DateTime $createdTo = null, ?int $page = 1, ?int $limit = 20)
    {
        $this->status = $status;
        $this->partyId = $partyId;
        $this->direction = $direction;
        $this->createdFrom = $createdFrom;
        $this->createdTo = $createdTo;
        $this->page = $page;
        $this->limit = $limit;
    }
}