<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** GetV0ContactsResponseBody - Default Response */
class GetV0ContactsResponseBody
{
    /**
     * $data
     *
     * @var array<Data> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\Now\Models\Operations\Data>')]
    public array $data;

    /**
     *
     * @var Meta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Meta')]
    public Meta $meta;

    /**
     * @param  array<Data>  $data
     * @param  Meta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, Meta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}