<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** GetV0ContactsResponseBody - Default Response */
class GetV0ContactsResponseBody
{
    /**
     * $data
     *
     * @var array<GetV0ContactsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\Now\Models\Operations\GetV0ContactsData>')]
    public array $data;

    /**
     *
     * @var GetV0ContactsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\GetV0ContactsMeta')]
    public GetV0ContactsMeta $meta;

    /**
     * @param  array<GetV0ContactsData>  $data
     * @param  GetV0ContactsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, GetV0ContactsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}