<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** GetWebhookResponseBody - Default Response */
class GetWebhookResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetWebhookData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetWebhookData')]
    public GetWebhookData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\GetWebhookMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\GetWebhookMeta')]
    public GetWebhookMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetWebhookData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\GetWebhookMeta  $meta
     * @phpstan-pure
     */
    public function __construct(GetWebhookData $data, GetWebhookMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}