<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b9091a6f1635
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum GetWebhookSubscribedEvent: string
{
    case StatementGenerated = 'STATEMENT_GENERATED';
}
