<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: df4b0273ddca
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class GetWebhookMeta
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * @param  \DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp)
    {
        $this->timestamp = $timestamp;
    }
}