<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ac7898208ae9
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListWebhooksSubscribedEvent: string
{
    case StatementGenerated = 'STATEMENT_GENERATED';
}
