<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListContactsData
{
    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListContactsEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListContactsEntityType')]
    public ListContactsEntityType $entityType;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListContactsLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListContactsLegalAddress')]
    public ListContactsLegalAddress $legalAddress;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\ListContactsBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListContactsBankAccount|null')]
    public ?ListContactsBankAccount $bankAccount = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public ?string $phoneNumber = null;

    /**
     * @param  string  $contactId
     * @param  \DateTime  $createdAt
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListContactsEntityType  $entityType
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListContactsLegalAddress  $legalAddress
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\ListContactsBankAccount  $bankAccount
     * @param  ?string  $companyName
     * @param  ?string  $email
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(string $contactId, \DateTime $createdAt, ListContactsEntityType $entityType, ListContactsLegalAddress $legalAddress, ?ListContactsBankAccount $bankAccount = null, ?string $companyName = null, ?string $email = null, ?string $firstName = null, ?string $lastName = null, ?string $phoneNumber = null)
    {
        $this->contactId = $contactId;
        $this->createdAt = $createdAt;
        $this->entityType = $entityType;
        $this->legalAddress = $legalAddress;
        $this->bankAccount = $bankAccount;
        $this->companyName = $companyName;
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
    }
}