<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class ListStatementsRequest
{
    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $originatorId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=originatorId')]
    public ?string $originatorId = null;

    /**
     *
     * @var ?int $periodMonth
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=periodMonth')]
    public ?int $periodMonth = null;

    /**
     *
     * @var ?int $periodYear
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=periodYear')]
    public ?int $periodYear = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?string  $cursor
     * @param  ?int  $limit
     * @param  ?string  $originatorId
     * @param  ?int  $periodMonth
     * @param  ?int  $periodYear
     * @phpstan-pure
     */
    public function __construct(?string $cursor = null, ?string $originatorId = null, ?int $periodMonth = null, ?int $periodYear = null, ?int $limit = 20)
    {
        $this->cursor = $cursor;
        $this->originatorId = $originatorId;
        $this->periodMonth = $periodMonth;
        $this->periodYear = $periodYear;
        $this->limit = $limit;
    }
}