<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class ListContactsRequest
{
    /**
     *
     * @var string $originatorId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  string  $originatorId
     * @param  ?string  $cursor
     * @param  ?int  $limit
     * @param  ?string  $search
     * @phpstan-pure
     */
    public function __construct(string $originatorId, ?string $cursor = null, ?string $search = null, ?int $limit = 20)
    {
        $this->originatorId = $originatorId;
        $this->cursor = $cursor;
        $this->search = $search;
        $this->limit = $limit;
    }
}