<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListStatementsData
{
    /**
     *
     * @var \DateTime $generatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('generatedAt')]
    public \DateTime $generatedAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var bool $pdfReady
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pdfReady')]
    public bool $pdfReady;

    /**
     *
     * @var int $periodMonth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periodMonth')]
    public int $periodMonth;

    /**
     *
     * @var int $periodYear
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periodYear')]
    public int $periodYear;

    /**
     *
     * @var string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    public string $timezone;

    /**
     *
     * @var float $totalDiscountRateMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalDiscountRateMinorUnits')]
    public float $totalDiscountRateMinorUnits;

    /**
     *
     * @var int $totalFeeCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalFeeCount')]
    public int $totalFeeCount;

    /**
     *
     * @var int $totalPaymentCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalPaymentCount')]
    public int $totalPaymentCount;

    /**
     *
     * @var float $totalProcessingVolumeMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalProcessingVolumeMinorUnits')]
    public float $totalProcessingVolumeMinorUnits;

    /**
     *
     * @var int $totalReturnCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalReturnCount')]
    public int $totalReturnCount;

    /**
     *
     * @var float $totalReturnFeesMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalReturnFeesMinorUnits')]
    public float $totalReturnFeesMinorUnits;

    /**
     *
     * @var float $totalReturnVolumeMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalReturnVolumeMinorUnits')]
    public float $totalReturnVolumeMinorUnits;

    /**
     *
     * @var float $totalServiceFeesMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalServiceFeesMinorUnits')]
    public float $totalServiceFeesMinorUnits;

    /**
     *
     * @var float $totalTransactionFeesMinorUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalTransactionFeesMinorUnits')]
    public float $totalTransactionFeesMinorUnits;

    /**
     *
     * @var ?int $sizeBytes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sizeBytes')]
    public ?int $sizeBytes;

    /**
     * @param  \DateTime  $generatedAt
     * @param  string  $id
     * @param  string  $originatorId
     * @param  bool  $pdfReady
     * @param  int  $periodMonth
     * @param  int  $periodYear
     * @param  string  $timezone
     * @param  float  $totalDiscountRateMinorUnits
     * @param  int  $totalFeeCount
     * @param  int  $totalPaymentCount
     * @param  float  $totalProcessingVolumeMinorUnits
     * @param  int  $totalReturnCount
     * @param  float  $totalReturnFeesMinorUnits
     * @param  float  $totalReturnVolumeMinorUnits
     * @param  float  $totalServiceFeesMinorUnits
     * @param  float  $totalTransactionFeesMinorUnits
     * @param  ?int  $sizeBytes
     * @phpstan-pure
     */
    public function __construct(\DateTime $generatedAt, string $id, string $originatorId, bool $pdfReady, int $periodMonth, int $periodYear, string $timezone, float $totalDiscountRateMinorUnits, int $totalFeeCount, int $totalPaymentCount, float $totalProcessingVolumeMinorUnits, int $totalReturnCount, float $totalReturnFeesMinorUnits, float $totalReturnVolumeMinorUnits, float $totalServiceFeesMinorUnits, float $totalTransactionFeesMinorUnits, ?int $sizeBytes = null)
    {
        $this->generatedAt = $generatedAt;
        $this->id = $id;
        $this->originatorId = $originatorId;
        $this->pdfReady = $pdfReady;
        $this->periodMonth = $periodMonth;
        $this->periodYear = $periodYear;
        $this->timezone = $timezone;
        $this->totalDiscountRateMinorUnits = $totalDiscountRateMinorUnits;
        $this->totalFeeCount = $totalFeeCount;
        $this->totalPaymentCount = $totalPaymentCount;
        $this->totalProcessingVolumeMinorUnits = $totalProcessingVolumeMinorUnits;
        $this->totalReturnCount = $totalReturnCount;
        $this->totalReturnFeesMinorUnits = $totalReturnFeesMinorUnits;
        $this->totalReturnVolumeMinorUnits = $totalReturnVolumeMinorUnits;
        $this->totalServiceFeesMinorUnits = $totalServiceFeesMinorUnits;
        $this->totalTransactionFeesMinorUnits = $totalTransactionFeesMinorUnits;
        $this->sizeBytes = $sizeBytes;
    }
}