<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListPaymentsPaymentRail: string
{
    case Ach = 'ACH';
    case Fednow = 'FEDNOW';
    case Fedwire = 'FEDWIRE';
    case Rtp = 'RTP';
    case Swift = 'SWIFT';
}
