<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** ListOriginatorsResponseBody - Default Response */
class ListOriginatorsResponseBody
{
    /**
     * $data
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsData>')]
    public array $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsMeta')]
    public ListOriginatorsMeta $meta;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsData>  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListOriginatorsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListOriginatorsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}