<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListContactsLegalAddress
{
    /**
     *
     * @var string $addressLine1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addressLine1')]
    public string $addressLine1;

    /**
     *
     * @var string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    public string $city;

    /**
     *
     * @var string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    public string $countryCode;

    /**
     *
     * @var string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
    public string $postalCode;

    /**
     *
     * @var string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    public string $state;

    /**
     *
     * @var ?string $addressLine2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addressLine2')]
    public ?string $addressLine2;

    /**
     * @param  string  $addressLine1
     * @param  string  $city
     * @param  string  $countryCode
     * @param  string  $postalCode
     * @param  string  $state
     * @param  ?string  $addressLine2
     * @phpstan-pure
     */
    public function __construct(string $addressLine1, string $city, string $countryCode, string $postalCode, string $state, ?string $addressLine2 = null)
    {
        $this->addressLine1 = $addressLine1;
        $this->city = $city;
        $this->countryCode = $countryCode;
        $this->postalCode = $postalCode;
        $this->state = $state;
        $this->addressLine2 = $addressLine2;
    }
}