<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** ListStatementsResponseBody - Default Response */
class ListStatementsResponseBody
{
    /**
     * $data
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\ListStatementsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\ListStatementsData>')]
    public array $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListStatementsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListStatementsMeta')]
    public ListStatementsMeta $meta;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\ListStatementsData>  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListStatementsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListStatementsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}