<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class ListPaymentsMeta
{
    /**
     *
     * @var Pagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Pagination')]
    public Pagination $pagination;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * @param  Pagination  $pagination
     * @param  \DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(Pagination $pagination, \DateTime $timestamp)
    {
        $this->pagination = $pagination;
        $this->timestamp = $timestamp;
    }
}