<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class ListOriginatorsRequest
{
    /**
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * @param  ?string  $search
     * @phpstan-pure
     */
    public function __construct(?string $search = null)
    {
        $this->search = $search;
    }
}