<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class ListOriginatorsBankAccount
{
    /**
     *
     * @var string $achAccountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achAccountNumber')]
    public string $achAccountNumber;

    /**
     *
     * @var string $achRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achRoutingNumber')]
    public string $achRoutingNumber;

    /**
     *
     * @var ListOriginatorsSubType $subType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListOriginatorsSubType')]
    public ListOriginatorsSubType $subType;

    /**
     *
     * @var ?string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankName')]
    public ?string $bankName;

    /**
     *
     * @var ?string $swiftCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('swiftCode')]
    public ?string $swiftCode;

    /**
     * @param  string  $achAccountNumber
     * @param  string  $achRoutingNumber
     * @param  ListOriginatorsSubType  $subType
     * @param  ?string  $bankName
     * @param  ?string  $swiftCode
     * @phpstan-pure
     */
    public function __construct(string $achAccountNumber, string $achRoutingNumber, ListOriginatorsSubType $subType, ?string $bankName = null, ?string $swiftCode = null)
    {
        $this->achAccountNumber = $achAccountNumber;
        $this->achRoutingNumber = $achRoutingNumber;
        $this->subType = $subType;
        $this->bankName = $bankName;
        $this->swiftCode = $swiftCode;
    }
}