<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3f586d339911
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListContactsEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
