<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** ListWebhooksResponseBody - Default Response */
class ListWebhooksResponseBody
{
    /**
     * $data
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\ListWebhooksData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\ListWebhooksData>')]
    public array $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListWebhooksMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListWebhooksMeta')]
    public ListWebhooksMeta $meta;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\ListWebhooksData>  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListWebhooksMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListWebhooksMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}