<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** ListPaymentsResponseBody - Default Response */
class ListPaymentsResponseBody
{
    /**
     * $data
     *
     * @var array<ListPaymentsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\Now\Models\Operations\ListPaymentsData>')]
    public array $data;

    /**
     *
     * @var ListPaymentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListPaymentsMeta')]
    public ListPaymentsMeta $meta;

    /**
     * @param  array<ListPaymentsData>  $data
     * @param  ListPaymentsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListPaymentsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}