<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 207d5cb5265c
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListPaymentsOriginatorEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
