<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 624727a18fb1
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListOriginatorsSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
