<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListPaymentsData
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsDirectionResponse $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsDirectionResponse')]
    public ListPaymentsDirectionResponse $direction;

    /**
     * In minor units (cents)
     *
     * @var int $feeAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeAmount')]
    public int $feeAmount;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsOriginator $originator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsOriginator')]
    public ListPaymentsOriginator $originator;

    /**
     * In minor units (cents)
     *
     * @var int $paymentAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentAmount')]
    public int $paymentAmount;

    /**
     *
     * @var string $paymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentId')]
    public string $paymentId;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentRail')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPaymentRail')]
    public ListPaymentsPaymentRail $paymentRail;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsStatusResponse $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsStatusResponse')]
    public ListPaymentsStatusResponse $status;

    /**
     *
     * @var ?\DateTime $completedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedAt')]
    public ?\DateTime $completedAt;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsContact $contact
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contact')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsContact|null')]
    public ?ListPaymentsContact $contact;

    /**
     *
     * @var ?string $externalPaymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalPaymentId')]
    public ?string $externalPaymentId;

    /**
     *
     * @var ?\DateTime $failedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failedAt')]
    public ?\DateTime $failedAt;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsFailureCode $failureCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsFailureCode|null')]
    public ?ListPaymentsFailureCode $failureCode;

    /**
     *
     * @var ?string $failureMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureMessage')]
    public ?string $failureMessage;

    /**
     *
     * @var ?string $paymentNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentNote')]
    public ?string $paymentNote;

    /**
     *
     * @var ?\DateTime $returnedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('returnedAt')]
    public ?\DateTime $returnedAt;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $currencyCode
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsDirectionResponse  $direction
     * @param  int  $feeAmount
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsOriginator  $originator
     * @param  int  $paymentAmount
     * @param  string  $paymentId
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPaymentRail  $paymentRail
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsStatusResponse  $status
     * @param  ?\DateTime  $completedAt
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsContact  $contact
     * @param  ?string  $externalPaymentId
     * @param  ?\DateTime  $failedAt
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsFailureCode  $failureCode
     * @param  ?string  $failureMessage
     * @param  ?string  $paymentNote
     * @param  ?\DateTime  $returnedAt
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $currencyCode, ListPaymentsDirectionResponse $direction, int $feeAmount, ListPaymentsOriginator $originator, int $paymentAmount, string $paymentId, ListPaymentsPaymentRail $paymentRail, ListPaymentsStatusResponse $status, ?\DateTime $completedAt = null, ?ListPaymentsContact $contact = null, ?string $externalPaymentId = null, ?\DateTime $failedAt = null, ?ListPaymentsFailureCode $failureCode = null, ?string $failureMessage = null, ?string $paymentNote = null, ?\DateTime $returnedAt = null)
    {
        $this->createdAt = $createdAt;
        $this->currencyCode = $currencyCode;
        $this->direction = $direction;
        $this->feeAmount = $feeAmount;
        $this->originator = $originator;
        $this->paymentAmount = $paymentAmount;
        $this->paymentId = $paymentId;
        $this->paymentRail = $paymentRail;
        $this->status = $status;
        $this->completedAt = $completedAt;
        $this->contact = $contact;
        $this->externalPaymentId = $externalPaymentId;
        $this->failedAt = $failedAt;
        $this->failureCode = $failureCode;
        $this->failureMessage = $failureMessage;
        $this->paymentNote = $paymentNote;
        $this->returnedAt = $returnedAt;
    }
}