<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** ListOriginatorsResponseBody - Default Response */
class ListOriginatorsResponseBody
{
    /**
     * $data
     *
     * @var array<ListOriginatorsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\Now\Models\Operations\ListOriginatorsData>')]
    public array $data;

    /**
     *
     * @var ListOriginatorsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListOriginatorsMeta')]
    public ListOriginatorsMeta $meta;

    /**
     * @param  array<ListOriginatorsData>  $data
     * @param  ListOriginatorsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListOriginatorsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}