<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c29c7140afc0
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListStatementsMeta
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListStatementsPagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListStatementsPagination')]
    public ListStatementsPagination $pagination;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListStatementsPagination  $pagination
     * @param  \DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(ListStatementsPagination $pagination, \DateTime $timestamp)
    {
        $this->pagination = $pagination;
        $this->timestamp = $timestamp;
    }
}