<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class ListPaymentsRequest
{
    /**
     *
     * @var ?\DateTime $createdFrom
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=createdFrom,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdFrom = null;

    /**
     *
     * @var ?\DateTime $createdTo
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=createdTo,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdTo = null;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\QueryParamDirection $direction
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=direction')]
    public ?QueryParamDirection $direction = null;

    /**
     *
     * @var ?string $originatorId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=originatorId')]
    public ?string $originatorId = null;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\QueryParamStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?QueryParamStatus $status = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * @param  ?\DateTime  $createdFrom
     * @param  ?\DateTime  $createdTo
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\QueryParamDirection  $direction
     * @param  ?int  $limit
     * @param  ?string  $originatorId
     * @param  ?int  $page
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\QueryParamStatus  $status
     * @phpstan-pure
     */
    public function __construct(?\DateTime $createdFrom = null, ?\DateTime $createdTo = null, ?QueryParamDirection $direction = null, ?string $originatorId = null, ?QueryParamStatus $status = null, ?int $limit = 20, ?int $page = 1)
    {
        $this->createdFrom = $createdFrom;
        $this->createdTo = $createdTo;
        $this->direction = $direction;
        $this->originatorId = $originatorId;
        $this->status = $status;
        $this->limit = $limit;
        $this->page = $page;
    }
}