<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** ListContactsResponseBody - Default Response */
class ListContactsResponseBody
{
    /**
     * $data
     *
     * @var array<\Luqra\LuqraNowPhp\Models\Operations\ListContactsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\ListContactsData>')]
    public array $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListContactsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListContactsMeta')]
    public ListContactsMeta $meta;

    /**
     * @param  array<\Luqra\LuqraNowPhp\Models\Operations\ListContactsData>  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListContactsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, ListContactsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}