<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 558c8fa57b64
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListContactsSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
