<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum ListWebhooksSubscribedEventEnum: string
{
    case PaymentAwaitingConfirmation = 'payment.awaiting_confirmation';
    case PaymentBlocked = 'payment.blocked';
    case PaymentCanceled = 'payment.canceled';
    case PaymentCompleted = 'payment.completed';
    case PaymentFailed = 'payment.failed';
    case PaymentFailedInFlight = 'payment.failed_in_flight';
    case PaymentProcessing = 'payment.processing';
    case PaymentQueued = 'payment.queued';
    case PaymentReturned = 'payment.returned';
    case StatementGenerated = 'statement.generated';
}
