<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class ListOriginatorsData
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var ListOriginatorsEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListOriginatorsEntityType')]
    public ListOriginatorsEntityType $entityType;

    /**
     *
     * @var ListOriginatorsLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListOriginatorsLegalAddress')]
    public ListOriginatorsLegalAddress $legalAddress;

    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?ListOriginatorsBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\ListOriginatorsBankAccount|null')]
    public ?ListOriginatorsBankAccount $bankAccount;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public ?string $firstName;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public ?string $lastName;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public ?string $phoneNumber;

    /**
     * @param  \DateTime  $createdAt
     * @param  ListOriginatorsEntityType  $entityType
     * @param  ListOriginatorsLegalAddress  $legalAddress
     * @param  string  $originatorId
     * @param  ?ListOriginatorsBankAccount  $bankAccount
     * @param  ?string  $companyName
     * @param  ?string  $email
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, ListOriginatorsEntityType $entityType, ListOriginatorsLegalAddress $legalAddress, string $originatorId, ?ListOriginatorsBankAccount $bankAccount = null, ?string $companyName = null, ?string $email = null, ?string $firstName = null, ?string $lastName = null, ?string $phoneNumber = null)
    {
        $this->createdAt = $createdAt;
        $this->entityType = $entityType;
        $this->legalAddress = $legalAddress;
        $this->originatorId = $originatorId;
        $this->bankAccount = $bankAccount;
        $this->companyName = $companyName;
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
    }
}