<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2d5ce3cfa292
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class ListPaymentsMeta
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPagination')]
    public ListPaymentsPagination $pagination;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\ListPaymentsPagination  $pagination
     * @param  \DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(ListPaymentsPagination $pagination, \DateTime $timestamp)
    {
        $this->pagination = $pagination;
        $this->timestamp = $timestamp;
    }
}