<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc4fda40ee8c
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum OriginatorSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
