<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum OriginatorSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
