<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class Pagination
{
    /**
     *
     * @var float $limit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('limit')]
    public float $limit;

    /**
     *
     * @var ?string $nextCursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nextCursor')]
    public ?string $nextCursor;

    /**
     * @param  float  $limit
     * @param  ?string  $nextCursor
     * @phpstan-pure
     */
    public function __construct(float $limit, ?string $nextCursor = null)
    {
        $this->limit = $limit;
        $this->nextCursor = $nextCursor;
    }
}