<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class Pagination
{
    /**
     *
     * @var bool $hasMore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasMore')]
    public bool $hasMore;

    /**
     *
     * @var float $limit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('limit')]
    public float $limit;

    /**
     *
     * @var float $page
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('page')]
    public float $page;

    /**
     *
     * @var float $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public float $total;

    /**
     * @param  bool  $hasMore
     * @param  float  $limit
     * @param  float  $page
     * @param  float  $total
     * @phpstan-pure
     */
    public function __construct(bool $hasMore, float $limit, float $page, float $total)
    {
        $this->hasMore = $hasMore;
        $this->limit = $limit;
        $this->page = $page;
        $this->total = $total;
    }
}