<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;

use Luqra\Now\Utils\SpeakeasyMetadata;
class PatchV0ContactsIdRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var PatchV0ContactsIdRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PatchV0ContactsIdRequestBody $requestBody;

    /**
     * @param  string  $id
     * @param  PatchV0ContactsIdRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, PatchV0ContactsIdRequestBody $requestBody)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}