<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class PatchV0ContactsIdRequestBody
{
    /**
     *
     * @var ?PatchV0ContactsIdBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PatchV0ContactsIdBankAccount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchV0ContactsIdBankAccount $bankAccount = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?PatchV0ContactsIdEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PatchV0ContactsIdEntityType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchV0ContactsIdEntityType $entityType = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?PatchV0ContactsIdLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PatchV0ContactsIdLegalAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchV0ContactsIdLegalAddress $legalAddress = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     * @param  ?PatchV0ContactsIdBankAccount  $bankAccount
     * @param  ?string  $email
     * @param  ?PatchV0ContactsIdEntityType  $entityType
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?PatchV0ContactsIdLegalAddress  $legalAddress
     * @param  ?string  $phoneNumber
     * @param  ?string  $companyName
     * @phpstan-pure
     */
    public function __construct(?PatchV0ContactsIdBankAccount $bankAccount = null, ?string $email = null, ?PatchV0ContactsIdEntityType $entityType = null, ?string $firstName = null, ?string $lastName = null, ?PatchV0ContactsIdLegalAddress $legalAddress = null, ?string $phoneNumber = null, ?string $companyName = null)
    {
        $this->bankAccount = $bankAccount;
        $this->email = $email;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->phoneNumber = $phoneNumber;
        $this->companyName = $companyName;
    }
}