<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class PatchV0ContactsIdData
{
    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var PatchV0ContactsIdContactsEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PatchV0ContactsIdContactsEntityType')]
    public PatchV0ContactsIdContactsEntityType $entityType;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var PatchV0ContactsIdContactsLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PatchV0ContactsIdContactsLegalAddress')]
    public PatchV0ContactsIdContactsLegalAddress $legalAddress;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?PatchV0ContactsIdContactsBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PatchV0ContactsIdContactsBankAccount|null')]
    public ?PatchV0ContactsIdContactsBankAccount $bankAccount = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public ?string $phoneNumber = null;

    /**
     * @param  string  $contactId
     * @param  PatchV0ContactsIdContactsEntityType  $entityType
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  PatchV0ContactsIdContactsLegalAddress  $legalAddress
     * @param  \DateTime  $updatedAt
     * @param  ?PatchV0ContactsIdContactsBankAccount  $bankAccount
     * @param  ?string  $companyName
     * @param  ?string  $email
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(string $contactId, PatchV0ContactsIdContactsEntityType $entityType, string $firstName, string $lastName, PatchV0ContactsIdContactsLegalAddress $legalAddress, \DateTime $updatedAt, ?PatchV0ContactsIdContactsBankAccount $bankAccount = null, ?string $companyName = null, ?string $email = null, ?string $phoneNumber = null)
    {
        $this->contactId = $contactId;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->updatedAt = $updatedAt;
        $this->bankAccount = $bankAccount;
        $this->companyName = $companyName;
        $this->email = $email;
        $this->phoneNumber = $phoneNumber;
    }
}