<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** PatchV0ContactsIdResponseBody - Default Response */
class PatchV0ContactsIdResponseBody
{
    /**
     *
     * @var PatchV0ContactsIdData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PatchV0ContactsIdData')]
    public PatchV0ContactsIdData $data;

    /**
     *
     * @var PatchV0ContactsIdMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PatchV0ContactsIdMeta')]
    public PatchV0ContactsIdMeta $meta;

    /**
     * @param  PatchV0ContactsIdData  $data
     * @param  PatchV0ContactsIdMeta  $meta
     * @phpstan-pure
     */
    public function __construct(PatchV0ContactsIdData $data, PatchV0ContactsIdMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}