<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


enum PatchV0ContactsIdContactsEntityType: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
