<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** PostV1PaymentsResponseBody - Default Response */
class PostV1PaymentsResponseBody
{
    /**
     *
     * @var PostV1PaymentsData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PostV1PaymentsData')]
    public PostV1PaymentsData $data;

    /**
     *
     * @var PostV1PaymentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PostV1PaymentsMeta')]
    public PostV1PaymentsMeta $meta;

    /**
     * @param  PostV1PaymentsData  $data
     * @param  PostV1PaymentsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(PostV1PaymentsData $data, PostV1PaymentsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}