<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** PostV0ContactsResponseBody - Default Response */
class PostV0ContactsResponseBody
{
    /**
     *
     * @var PostV0ContactsData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PostV0ContactsData')]
    public PostV0ContactsData $data;

    /**
     *
     * @var PostV0ContactsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\PostV0ContactsMeta')]
    public PostV0ContactsMeta $meta;

    /**
     * @param  PostV0ContactsData  $data
     * @param  PostV0ContactsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(PostV0ContactsData $data, PostV0ContactsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}