<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class PostV1ContactsRequestBody
{
    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var Address $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\Address')]
    public Address $address;

    /**
     *
     * @var BankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\BankAccount')]
    public BankAccount $bankAccount;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  string  $originatorId
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $email
     * @param  Address  $address
     * @param  BankAccount  $bankAccount
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(string $originatorId, string $firstName, string $lastName, string $email, Address $address, BankAccount $bankAccount, ?string $phoneNumber = null)
    {
        $this->originatorId = $originatorId;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->address = $address;
        $this->bankAccount = $bankAccount;
        $this->phoneNumber = $phoneNumber;
    }
}