<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class PostV0ContactsRequestBody
{
    /**
     *
     * @var BankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\BankAccount')]
    public BankAccount $bankAccount;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var EntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\EntityType')]
    public EntityType $entityType;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var LegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\LegalAddress')]
    public LegalAddress $legalAddress;

    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  BankAccount  $bankAccount
     * @param  string  $email
     * @param  EntityType  $entityType
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  LegalAddress  $legalAddress
     * @param  string  $originatorId
     * @param  ?string  $companyName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(BankAccount $bankAccount, string $email, EntityType $entityType, string $firstName, string $lastName, LegalAddress $legalAddress, string $originatorId, ?string $companyName = null, ?string $phoneNumber = null)
    {
        $this->bankAccount = $bankAccount;
        $this->email = $email;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->originatorId = $originatorId;
        $this->companyName = $companyName;
        $this->phoneNumber = $phoneNumber;
    }
}