<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** PostV1ContactsResponseBody - Default Response */
class PostV1ContactsResponseBody
{
    /**
     *
     * @var Data $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Data')]
    public Data $data;

    /**
     *
     * @var Meta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Meta')]
    public Meta $meta;

    /**
     * @param  Data  $data
     * @param  Meta  $meta
     * @phpstan-pure
     */
    public function __construct(Data $data, Meta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}