<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class PostV1PaymentsRequestBody
{
    /**
     *
     * @var string $originatorId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originatorId')]
    public string $originatorId;

    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var float $paymentAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentAmount')]
    public float $paymentAmount;

    /**
     *
     * @var Direction $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\Direction')]
    public Direction $direction;

    /**
     *
     * @var ?string $externalPaymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalPaymentId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalPaymentId = null;

    /**
     *
     * @var ?string $paymentNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentNote')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentNote = null;

    /**
     * @param  string  $originatorId
     * @param  string  $contactId
     * @param  float  $paymentAmount
     * @param  Direction  $direction
     * @param  ?string  $externalPaymentId
     * @param  ?string  $paymentNote
     * @phpstan-pure
     */
    public function __construct(string $originatorId, string $contactId, float $paymentAmount, Direction $direction, ?string $externalPaymentId = null, ?string $paymentNote = null)
    {
        $this->originatorId = $originatorId;
        $this->contactId = $contactId;
        $this->paymentAmount = $paymentAmount;
        $this->direction = $direction;
        $this->externalPaymentId = $externalPaymentId;
        $this->paymentNote = $paymentNote;
    }
}