<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class PostV1PaymentsData
{
    /**
     *
     * @var string $paymentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentId')]
    public string $paymentId;

    /**
     * @param  string  $paymentId
     * @phpstan-pure
     */
    public function __construct(string $paymentId)
    {
        $this->paymentId = $paymentId;
    }
}