<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** PostV0PaymentsResponseBody - Default Response */
class PostV0PaymentsResponseBody
{
    /**
     *
     * @var PostV0PaymentsData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PostV0PaymentsData')]
    public PostV0PaymentsData $data;

    /**
     *
     * @var PostV0PaymentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\PostV0PaymentsMeta')]
    public PostV0PaymentsMeta $meta;

    /**
     * @param  PostV0PaymentsData  $data
     * @param  PostV0PaymentsMeta  $meta
     * @phpstan-pure
     */
    public function __construct(PostV0PaymentsData $data, PostV0PaymentsMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}