<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4a037036f10c
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;



enum QueryParamDirection: string
{
    case Inbound = 'INBOUND';
    case Outbound = 'OUTBOUND';
}
