<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;



enum QueryParamStatus: string
{
    case AwaitingConfirmation = 'AWAITING_CONFIRMATION';
    case Blocked = 'BLOCKED';
    case Canceled = 'CANCELED';
    case Completed = 'COMPLETED';
    case Failed = 'FAILED';
    case FailedInFlight = 'FAILED_IN_FLIGHT';
    case PendingCustomerRetry = 'PENDING_CUSTOMER_RETRY';
    case Processing = 'PROCESSING';
    case Queued = 'QUEUED';
    case Returned = 'RETURNED';
}
