<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class TestWebhookData
{
    /**
     *
     * @var float $durationMs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('durationMs')]
    public float $durationMs;

    /**
     *
     * @var bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public ?string $error;

    /**
     *
     * @var ?float $statusCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
    public ?float $statusCode;

    /**
     * @param  float  $durationMs
     * @param  bool  $success
     * @param  ?string  $error
     * @param  ?float  $statusCode
     * @phpstan-pure
     */
    public function __construct(float $durationMs, bool $success, ?string $error = null, ?float $statusCode = null)
    {
        $this->durationMs = $durationMs;
        $this->success = $success;
        $this->error = $error;
        $this->statusCode = $statusCode;
    }
}