<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3d9e9ceb7d52
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** TestWebhookResponseBody - Default Response */
class TestWebhookResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\TestWebhookData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\TestWebhookData')]
    public TestWebhookData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\TestWebhookMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\TestWebhookMeta')]
    public TestWebhookMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\TestWebhookData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\TestWebhookMeta  $meta
     * @phpstan-pure
     */
    public function __construct(TestWebhookData $data, TestWebhookMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}