<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class TestWebhookRequestBody
{
    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\EventType $eventType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\EventType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EventType $eventType = null;

    /**
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\EventType  $eventType
     * @phpstan-pure
     */
    public function __construct(?EventType $eventType = null)
    {
        $this->eventType = $eventType;
    }
}