<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** UpdateWebhookResponseBody - Default Response */
class UpdateWebhookResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookData')]
    public UpdateWebhookData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookMeta')]
    public UpdateWebhookMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookMeta  $meta
     * @phpstan-pure
     */
    public function __construct(UpdateWebhookData $data, UpdateWebhookMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}