<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


class UpdateContactRequestBody
{
    /**
     *
     * @var ?UpdateContactBankAccount $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\UpdateContactBankAccount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactBankAccount $bankAccount = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?UpdateContactEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\UpdateContactEntityType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactEntityType $entityType = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?UpdateContactLegalAddress $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\UpdateContactLegalAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactLegalAddress $legalAddress = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     * @param  ?UpdateContactBankAccount  $bankAccount
     * @param  ?string  $email
     * @param  ?UpdateContactEntityType  $entityType
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?UpdateContactLegalAddress  $legalAddress
     * @param  ?string  $phoneNumber
     * @param  ?string  $companyName
     * @phpstan-pure
     */
    public function __construct(?UpdateContactBankAccount $bankAccount = null, ?string $email = null, ?UpdateContactEntityType $entityType = null, ?string $firstName = null, ?string $lastName = null, ?UpdateContactLegalAddress $legalAddress = null, ?string $phoneNumber = null, ?string $companyName = null)
    {
        $this->bankAccount = $bankAccount;
        $this->email = $email;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->phoneNumber = $phoneNumber;
        $this->companyName = $companyName;
    }
}