<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


/** UpdateContactResponseBody - Default Response */
class UpdateContactResponseBody
{
    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateContactData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactData')]
    public UpdateContactData $data;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateContactMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactMeta')]
    public UpdateContactMeta $meta;

    /**
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateContactData  $data
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateContactMeta  $meta
     * @phpstan-pure
     */
    public function __construct(UpdateContactData $data, UpdateContactMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}