<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class UpdateContactRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateContactRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public UpdateContactRequestBody $body;

    /**
     * @param  string  $id
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateContactRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, UpdateContactRequestBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}