<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f2821c47ecf6
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum UpdateContactEntityTypeResponse: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
