<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class UpdateWebhookRequestBody
{
    /**
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * $subscribedEvents
     *
     * @var ?array<\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventRequestEnum> $subscribedEvents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscribedEvents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventRequestEnum>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $subscribedEvents = null;

    /**
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * @param  ?bool  $enabled
     * @param  ?array<\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventPaymentWildcardRequest|\Luqra\LuqraNowPhp\Models\Operations\UpdateWebhookSubscribedEventRequestEnum>  $subscribedEvents
     * @param  ?string  $url
     * @param  ?string  $label
     * @phpstan-pure
     */
    public function __construct(?bool $enabled = null, ?array $subscribedEvents = null, ?string $url = null, ?string $label = null)
    {
        $this->enabled = $enabled;
        $this->subscribedEvents = $subscribedEvents;
        $this->url = $url;
        $this->label = $label;
    }
}