<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class UpdateContactData
{
    /**
     *
     * @var string $contactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contactId')]
    public string $contactId;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeResponse $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeResponse')]
    public UpdateContactEntityTypeResponse $entityType;

    /**
     *
     * @var \Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressResponse $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressResponse')]
    public UpdateContactLegalAddressResponse $legalAddress;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountResponse $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountResponse|null')]
    public ?UpdateContactBankAccountResponse $bankAccount = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public ?string $phoneNumber = null;

    /**
     * @param  string  $contactId
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeResponse  $entityType
     * @param  \Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressResponse  $legalAddress
     * @param  \DateTime  $updatedAt
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountResponse  $bankAccount
     * @param  ?string  $companyName
     * @param  ?string  $email
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(string $contactId, UpdateContactEntityTypeResponse $entityType, UpdateContactLegalAddressResponse $legalAddress, \DateTime $updatedAt, ?UpdateContactBankAccountResponse $bankAccount = null, ?string $companyName = null, ?string $email = null, ?string $firstName = null, ?string $lastName = null, ?string $phoneNumber = null)
    {
        $this->contactId = $contactId;
        $this->entityType = $entityType;
        $this->legalAddress = $legalAddress;
        $this->updatedAt = $updatedAt;
        $this->bankAccount = $bankAccount;
        $this->companyName = $companyName;
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
    }
}