<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


class UpdateContactRequestBody
{
    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountRequest $bankAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactBankAccountRequest $bankAccount = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeRequest $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entityType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactEntityTypeRequest $entityType = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressRequest $legalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legalAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateContactLegalAddressRequest $legalAddress = null;

    /**
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactBankAccountRequest  $bankAccount
     * @param  ?string  $email
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactEntityTypeRequest  $entityType
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?\Luqra\LuqraNowPhp\Models\Operations\UpdateContactLegalAddressRequest  $legalAddress
     * @param  ?string  $companyName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(?UpdateContactBankAccountRequest $bankAccount = null, ?string $email = null, ?UpdateContactEntityTypeRequest $entityType = null, ?string $firstName = null, ?string $lastName = null, ?UpdateContactLegalAddressRequest $legalAddress = null, ?string $companyName = null, ?string $phoneNumber = null)
    {
        $this->bankAccount = $bankAccount;
        $this->email = $email;
        $this->entityType = $entityType;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->legalAddress = $legalAddress;
        $this->companyName = $companyName;
        $this->phoneNumber = $phoneNumber;
    }
}