<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 38581b215d4d
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum UpdateWebhookSubscribedEventResponse: string
{
    case StatementGenerated = 'STATEMENT_GENERATED';
}
