<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c48a90edb65
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Operations;


enum UpdateContactEntityTypeRequest: string
{
    case Business = 'BUSINESS';
    case Individual = 'INDIVIDUAL';
}
