<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


enum UpdateContactContactsSubType: string
{
    case Checking = 'CHECKING';
    case Savings = 'SAVINGS';
}
