<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;


/** UpdateContactResponseBody - Default Response */
class UpdateContactResponseBody
{
    /**
     *
     * @var UpdateContactData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\UpdateContactData')]
    public UpdateContactData $data;

    /**
     *
     * @var UpdateContactMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Luqra\Now\Models\Operations\UpdateContactMeta')]
    public UpdateContactMeta $meta;

    /**
     * @param  UpdateContactData  $data
     * @param  UpdateContactMeta  $meta
     * @phpstan-pure
     */
    public function __construct(UpdateContactData $data, UpdateContactMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}