<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\Now\Models\Operations;

use Luqra\Now\Utils\SpeakeasyMetadata;
class UpdateContactRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var UpdateContactRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public UpdateContactRequestBody $requestBody;

    /**
     * @param  string  $id
     * @param  UpdateContactRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, UpdateContactRequestBody $requestBody)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}