<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97a086b67b34
 */


declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Utils\Retry;

class RetryConfigNone extends RetryConfig
{
    public RetryStrategy $strategy = RetryStrategy::NONE;
}
