<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86ede313b205
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Utils\Retry;

abstract class RetryConfig
{
    public RetryStrategy $strategy;
}
