<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp\Models\Components;

use Luqra\LuqraNowPhp\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $bearerAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public string $bearerAuth;

    /**
     * @param  string  $bearerAuth
     * @phpstan-pure
     */
    public function __construct(string $bearerAuth)
    {
        $this->bearerAuth = $bearerAuth;
    }
}