<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\LuqraNowPhp;



/** LuqraNow - Luqra Now API: External API for Luqra Now */
class LuqraNow
{
    public const SERVERS = [
        /** Sandbox */
        'https://staging.api.now.luqra.com',
        /** Production */
        'https://api.now.luqra.com',
    ];

    /**
     * Contact management endpoints
     *
     * @var Contacts $$contacts
     */
    public Contacts $contacts;

    /**
     * Originator endpoints
     *
     * @var Originators $$originators
     */
    public Originators $originators;

    /**
     * Payment intent endpoints
     *
     * @var Payments $$payments
     */
    public Payments $payments;

    /**
     * Monthly statement endpoints
     *
     * @var Statements $$statements
     */
    public Statements $statements;

    /**
     * Webhook endpoint management
     *
     * @var Webhooks $$webhooks
     */
    public Webhooks $webhooks;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return LuqraNowBuilder
     */
    public static function builder(): LuqraNowBuilder
    {
        return new LuqraNowBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->contacts = new Contacts($this->sdkConfiguration);
        $this->originators = new Originators($this->sdkConfiguration);
        $this->payments = new Payments($this->sdkConfiguration);
        $this->statements = new Statements($this->sdkConfiguration);
        $this->webhooks = new Webhooks($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}