<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Luqra\NowPhp;



/** LuqraNow - Luqra NOW API: External API for Luqra NOW */
class LuqraNow
{
    public const SERVERS = [
        /** Test */
        'https://staging.api.now.luqra.com',
        /** Production */
        'https://api.now.luqra.com',
    ];

    /**
     * Contact management endpoints
     *
     * @var Contacts $$contacts
     */
    public Contacts $contacts;

    /**
     * Payment intent endpoints
     *
     * @var Payments $$payments
     */
    public Payments $payments;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return LuqraNowBuilder
     */
    public static function builder(): LuqraNowBuilder
    {
        return new LuqraNowBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->contacts = new Contacts($this->sdkConfiguration);
        $this->payments = new Payments($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}